package com.paystream.auth.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "merchant_profiles")
public class MerchantProfile {

	/*
	 * Unique business identifier for the merchant.
	 *
	 * This ID is generated by Auth Service and can later be embedded in payment
	 * links or QR codes.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long merchantId;

	/*
	 * Every MerchantProfile belongs to exactly one User account.
	 *
	 * The User represents authentication/identity. MerchantProfile represents
	 * merchant-specific business data.
	 */
	@OneToOne(optional = false)
	@JoinColumn(name = "user_id", nullable = false, unique = true)
	private User user;

	@Column(nullable = false, length = 150)
	private String businessName;

	@Column(nullable = false, length = 100)
	private String category;

	/*
	 * A newly registered merchant is not automatically verified.
	 *
	 * Transaction Service will later check this status before accepting payments
	 * for the merchant.
	 */
	@Column(nullable = false)
	private boolean verified = false;

	/*
	 * Required by JPA.
	 */
	protected MerchantProfile() {
	}

	public MerchantProfile(User user, String businessName, String category) {

		this.user = user;
		this.businessName = businessName;
		this.category = category;
		this.verified = false;
	}

	public Long getMerchantId() {
		return merchantId;
	}

	public User getUser() {
		return user;
	}

	public String getBusinessName() {
		return businessName;
	}

	public String getCategory() {
		return category;
	}

	public boolean isVerified() {
		return verified;
	}

	public void setVerified(boolean verified) {
		this.verified = verified;
	}
}